### PR TITLE
Migrate project to AndroidX

### PR DESCRIPTION
**Pull request by wesselbarten**
Resolves issue #352
I have made use of the internal migrate to AndroidX option in Android Studio to accomplish this

### CODE REVIEW

**Comment by wesselbarten** [comment]
Hi I was wondering when are you going to review / merge this PR? Your library is outdated and really needs some updates....

**Comment by aditrioka** [comment]
please Applozic team, we all need to upgrade to androidx. Please review it and update the library.

**Comment by wesselbarten** [comment]
Thank you for the response, I wasn't aware there was a bug in the Google Maps SDK. I also haven't tested if the Google Maps part still works. But since the bug has been resolved accordingly to issuetracker you referenced, you might want to apply a fix for that as well. When I have time I can also look into it.

**Comment by aditrioka** [comment]
Is there any update for this issue?

**Comment by reytum** [comment]
@aditrioka We are testing the changes on our side. Once we are done with the testing, we will merge the PR release a new version of the SDK.

**Pull request merged**
